### ISSUE TITLE
Missing Container

### ISSUE THREAD

**Issue by DaveInTO** [slashsBin/phabulous#1]
[Mon Jan 09 15:13:49.391760 2017] [:error] [pid 28104] [client 76.9.206.238:3900] PHP Fatal error:  Uncaught PhutilMissingSymbolException: Failed to load class or interface 'Container': the class or interface 'Container' is not defined in the library map for any loaded phutil library.\n\nIf you are not a developer, this almost always means that a library is out of date. For example, you may have upgraded `phabricator` without upgrading `libphutil`, or vice versa. It might also mean that you need to restart Apache or PHP-FPM. Make sure all libraries are up to date and all services have been restarted.\n\nIf you are a developer and this symbol was recently added or moved, your library map may need to be rebuilt. You can rebuild the map by running 'arc liberate'. For more information, see:\n\nhttps://secure.phabricator.com/book/phabcontrib/article/adding_new_classes/ in /var/www/phabulous/vendor/phacility/libphutil/src/__phutil_library_init__.php:25\nStack trace:\n#0 [internal function]: __phutil_autoload('Container')\n#1 [internal function]: spl_autoload_call('Container')\n#2 /var/www/phabulous/vendor/symfony/symfony/s in /var/www/phabulous/vendor/phacility/libphutil/src/__phutil_library_init__.php on line 25

**Comment by slashsbin** [comment]
It's a known issue with `libphutil`, as the author does not believe in Composer!
You can read more here: [Why doesn't Phabricator (or Arcanist, or libphutil) support Composer?](https://secure.phabricator.com/T6012)
But using the Symfony's DEV Environment should work: if you are using bundled(`etc/nginx/sites-available/phabulous.conf`) NginX configuration then browsing to http://phabulous.localhost/app_dev.php/ should do it.
Currently I'm working on dropping `libphutil` as dependency in favor of using Guzzle with Conduit APIs directly. Any other ideas are appreciated.

**Comment by DaveInTO** [comment]
I've tried that..I;m then prompted for a username/password.Is this supposed to be my Phab username passsword? We use google auth.
ThanksDave

**Comment by slashsbin** [comment]
Default Username/Password is `admin`. Actually it does nothing(No Access-Level or similar concept) now.
It's not your phabricator username/password yet, phabulous currently only supports [in-memory](https://github.com/slashsBin/phabulous/blob/master/app/config/security.yml) username/passwords. Supporting phabricator OAuth is the next step.

**Comment by JeanFred** [comment]
I have ran into this as well, after building that app using Docker.

Have to say − it’s a bit unclear to me what the issue is ; because the latest version of libphutil was being pulled by Composer (I did check). I also tried checking out an old version of libphutil (eg from Aug 2016 when that app was first written) but got the same issue?

Using app_dev.php did sidestep the problem (not exactly sure how? Does it then not need libphutil at all?) − the Symfony app loads but displays no data whatsoever. It’s unclear to me where the issue is config, on the Gantt side or on the Phab side or in my setup.

(I understand this app is unmaintained so I’d be grateful for any pointers :)

**Comment by slashsbin** [comment]
@JeanFred 
First please note that Phabulous is no longer in active development nor is maintained anymore, so I'll recommend reconsidering using it.

Phabulous is a standalone Symfony web app, not a plugin/extension for phabricator. This means you should install it separately, then configure it to connect to your phabricator instance via bots.
Installation steps are located in the project's readme file [here](https://github.com/slashsBin/phabulous#install-phabulous). We assume you already know how to install a Symfony app, if not follow their original guide [here](https://symfony.com/doc/current/setup.html#installing-an-existing-symfony-application). There is also a [sample](https://github.com/slashsBin/phabulous/blob/master/etc/nginx/sites-available/phabulous.conf) NginX webserver config in the project repository, which will publish phabulous on your machine at http://phabulous.localhost, make sure to change it to match your setup(server name, the path to project, ...).

After setting up, there will be a new file located in "app/config/parameters.yml". Set your phabricator bot spec in this file to allow phabulous to connect to phabricator.

The idea of bots and usage of maniphest queries is to dynamically create phabulous chart data directly from phabricator, by first creating a sample maniphest query(let's say all the tasks currently defined in phabricator) and configure this query in phabulous to draw its chart from it, then you can change/update the query in phabricator(let's say filter it by a specific project) and refresh the chart to see it with new data.

Please also see [my comment above](#issuecomment-271412972).

Hope this was of any help.

**Comment by JeanFred** [comment]
@slashsBin Thank you for the answer!

Right, I do understand that this is a separate Symfony app. As I said, I run it using Docker containers (one for Nginx, one for PHP) separate from the Phabricator instance. If you are interested, you can see the setup at https://github.com/JeanFred/docker-phabulous.
