### ISSUE TITLE
support php7

### ISSUE THREAD

**Issue by mygon0172** [slashsBin/phabulous#2]
Hi slashsBin
Phabricator does not support php7
Https://secure.phabricator.com/T12101

This source says PHP7 is required
Is that right?

Thank you.

**Comment by slashsbin** [comment]
Yes Phabricator does not support PHP7 yet, but Phabulous does not include Phabricator's source-code.
Actually it's a Symfony App, so it supports PHP7 and it uses Phabricator Web API(Conduit) to interact with Phabricator.

**Comment by slashsbin** [comment]
By the way, I'm working to remove the use of `libphutil` in Phabulous as it does not support Composer.

**Comment by mygon0172** [comment]
Hi slashsBin
Thank you for answer.
I understand the Web API (Conduit)

There was a problem installing the Symfony App
```
# composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 11 installs, 16 updates, 0 removals
~~~       
  - Updating doctrine/doctrine-bundle (1.6.4 => 1.6.7) Downloading: 100%         
  - Installing phacility/libphutil (20160828) Cloning stable
    stable is gone (history was rewritten?)
```
I wish I had good results.

Thank you.

**Comment by slashsbin** [comment]
Try removing the `vendor/` directory and rerunning `composer install`, maybe that helps.
